name: Validation

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    name: Validate Databricks Bundle
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: databricks

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate bundle
        run: databricks bundle validate -t dev